version: "3.1"
services:
  app:
    build: ./server
    env_file: .env
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080
    links:
      - mongo
      - redis
  static:
    build: ./client
    env_file: .env
    ports:
      - 8000
    volumes:
      - ./client:/usr/src/static
      - /usr/src/static/node_modules
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data
  nginx:
    build: ./nginx
    links:
      - app:app
      - static:static
    ports:
      - 80:80
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data:/data

